services:
  app:
    build: .
    restart: always
    ports:
      - 80:8000
    command: >
      sh -c "python -m pip install Pillow &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on: 
      db:
        condition: service_healthy          #

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: root
    healthcheck:                            #
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]   #
      interval: 10s                         #
      timeout: 5s                           #
      retries: 5                            #


