# Generated by Django 4.2.4 on 2023-08-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='from_user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='post_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='notification',
            name='to_user',
            field=models.CharField(max_length=100),
        ),
    ]
