# Generated by Django 4.2.4 on 2023-08-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_notification_from_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='post_id',
        ),
    ]
